name: Build

on:
  push:
    branches:
      - main

jobs:
  build_105:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.105'
      - run:
          - dotnet --version
          - dotnet run
          - dotnet fsi script.fsx
  build_204:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.204'
      - run:
          - dotnet --version
          - dotnet run
          - dotnet fsi script.fsx
  build_300:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.300'
      - run:
          - dotnet --version
          - dotnet run
          - dotnet fsi script.fsx
