name: Build

on:
  push:
    branches: [ $default-branch ]

jobs:
  build_204:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.204'
      - run: dotnet build 
  build_300:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.300'
      - run: dotnet build 
